[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"
  BUILD_TRIGGER = "2025-01-17-3"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
