services:
  - type: web
    name: alwahis-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      cd /opt/render/project/src && python3 -c "from app import db; db.create_all()"
      cd /opt/render/project/src && gunicorn app:app --log-level debug --workers=2 --threads=4 --timeout=60
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
